### ISSUE TITLE
Test for Controller.Submit() broken

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#92] opened 2016-03-14 17:17 UTC
The test as it stands should :one: block forever, as the unit submitted is never returned by the fleet mock and :two: should at some point return that unit.

**Comment by JosephSalisbury** [comment] 2016-03-16 09:38
I'm assuming this is a symptom of #91?

**Comment by zeisss** [comment] 2016-03-16 09:43
Unclear to me. #91 is exactly the opposite of this. here I would it expect to bock, but it does not. in #91 it blocks, but it should not.

**Comment by JosephSalisbury** [comment] 2016-03-16 09:44
Okay, I'll fix #91 today, and then we can see where we end up with this issue, as well as #96

**Comment by JosephSalisbury** [comment] 2016-03-17 14:04
@zeisss i don't know what this issue requires.

**Comment by zeisss** [comment] 2016-03-17 14:16
Can you look at the controller.Submit test? There is an inconsistency in the test setup, which when you think about it - should mean that the test SHOULD block forever.

**Comment by JosephSalisbury** [comment] 2016-03-21 15:58
If you're talking about https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L547, I can't say I see it.

**Comment by zeisss** [comment] 2016-03-21 16:03
Look at submit please. https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L518 vs https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L529

**Comment by Nesurion** [comment] 2016-03-30 09:01
works as intended, but test coverage was bad. Fixed with #185

**Closed as completed by Nesurion** 2016-03-30 09:01 UTC
Labels: kind/bug
